/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.parsers.MovieParsers;
import hr.algebra.utilities.MessageUtils;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Paulo
 */
public class JPanelAdminCenter extends javax.swing.JPanel {
    
 private static final String ADMIN_PANEL = "Admin panel";
 private static final String ASSETS_PATH = "assets";
 
 private Repository repository;
 
    public JPanelAdminCenter() {
        initComponents();
         init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteData = new javax.swing.JButton();
        btnUploadData = new javax.swing.JButton();
        lbWelcome = new javax.swing.JLabel();

        btnDeleteData.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteData.setText("Delete");
        btnDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDataActionPerformed(evt);
            }
        });

        btnUploadData.setBackground(new java.awt.Color(0, 51, 153));
        btnUploadData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUploadData.setText("Upload ");
        btnUploadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadDataActionPerformed(evt);
            }
        });

        lbWelcome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbWelcome.setText("Welcome to the Admin panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnUploadData)
                .addGap(130, 130, 130)
                .addComponent(btnDeleteData, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUploadData, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteData, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDataActionPerformed
      
 if (MessageUtils.showConfirmDialog
        ("Data deletion", "Are you sure you want to delete all data?")) {
            try {
                deleteAllData();
            } catch (Exception ex) {
                Logger.getLogger(JPanelAdminCenter.class.getName())
                        .log(Level.SEVERE, null, ex);
                MessageUtils
                        .showErrorMessage
        (ADMIN_PANEL, "Error while data deletion!");
            }
        }
    }//GEN-LAST:event_btnDeleteDataActionPerformed

    private void btnUploadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadDataActionPerformed
        try {
    
    int maxMovieId = repository.maxMovieId().orElse(0);
    int maxPersonId = repository.maxPersonId().orElse(0);

   
            MovieParsers.parse(maxMovieId, maxPersonId);
} catch (Exception ex) {
   
     Logger
             .getLogger
        (JPanelAdminCenter.class.getName())
             .log(Level.SEVERE, null, ex);
     
            MessageUtils
                    .showErrorMessage
        (ADMIN_PANEL, "Error while uploading movies!");
}
    }//GEN-LAST:event_btnUploadDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteData;
    private javax.swing.JButton btnUploadData;
    private javax.swing.JLabel lbWelcome;
    // End of variables declaration//GEN-END:variables

    private void init() {
        try {
   
    initRepository();
} catch (Exception ex) {
  
    Logger.getLogger(JPanelAdminCenter.class.getName())
            .log(Level.SEVERE, null, ex);
            MessageUtils
           .showErrorMessage
        (ADMIN_PANEL, "Error initializing form!");
            
            
            System.exit(1);
}
    }

    private void initRepository() {
        repository = RepositoryFactory.getRepository();
    }

    private void deleteAllData() throws Exception {
         repository.deleteAllData();
        deleteAssets(ASSETS_PATH);
    }

    private void deleteAssets(String ASSETS_PATH) {
       try {
            Path directory = Paths.get(ASSETS_PATH);

            if (Files.exists(directory) && Files.isDirectory(directory)) {
                File[] files = directory.toFile().listFiles();

                if (files != null) {
                    for (File file : files) {
                        if (file.isFile()) {
                            file.delete();
                        }
                    }
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(JPanelAdminCenter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
