/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.login.LoginCallBack;
import javax.swing.JPanel;



/**
 *
 * @author Paulo
 */
public class MovieManager extends javax.swing.JFrame implements LoginCallBack{
    private static final String LOGIN_PANEL = "Login";
    private static final String CRUD_PEOPLE = "Edit people";
    private static final String CRUD_MOVIES = "Edit movies";
    private static final String ADMIN_PANEL = "Admin panel";
    private static final String MAIN_PANEL = "Movie manager";
    
    
    
    JPanel loginPanel = new JPanelLogin(this);
    JPanel editPeoplePanel = new JPanelCRUDPeople();
    JPanel editMoviesPanel = new JPanelCRUDMovies();
    JPanel adminPanel = new JPanelAdminCenter();

    /**
     * Creates new form MovieManager
     */
    public MovieManager() {
        setDefaultCloseOperation(MovieManager.EXIT_ON_CLOSE);
        setTitle(MAIN_PANEL);
        initComponents();
        loadLogin();
        setOtherPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MovieManager().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    @Override
    public void AdminLogin() {
      loadPanels(0);
    }

    @Override
    public void UserLogin() {
        loadPanels(1);

    }

    private void loadLogin() {
        tpContent.addTab(LOGIN_PANEL, loginPanel);
    }

    private void setOtherPanels() {
        tpContent.addTab(CRUD_MOVIES, editMoviesPanel);
        tpContent.addTab(CRUD_PEOPLE, editPeoplePanel);
        tpContent.addTab(ADMIN_PANEL, adminPanel);
        
        for (int i = 1; i < tpContent.getTabCount(); i++) {
            tpContent.setEnabledAt(i, false);
        }
    }

    private void loadPanels(int j) {
        if (j == 0) {
            tpContent.setSelectedComponent(adminPanel);
        }
        else if (j == 1) {
            tpContent.setSelectedComponent(editMoviesPanel);
        }
        for (int i = 1; i < tpContent.getTabCount() - j; i++) {
            tpContent.setEnabledAt(i, true);
        }
        tpContent.setEnabledAt(0, false);
    }


}
